# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ESPI Cookbook
description: > # this means to ignore newlines until "baseurl:"
  ESPI Cookbook is the creation of a cooking book by members of Edenspiekermann
  as part of Maker Days 2016, as an attempt to learn more about HTML and CSS
  web languages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
collections:
  recipes:
    output: true
    permalink: /recipes/:path/


# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass
